export const SAMPLE_BOOKS = [
  {
    id: "1",
    title: "فلسفة العمارة في المجلس الحديث",
    author: "د. إبراهيم الفاسي",
    price: 85,
    oldPrice: 110,
    description: "يقدم هذا الكتاب دراسة متعمقة في تاريخ وتطور المجلس العربي، وكيف تحول من فضاء تقليدي بسيط إلى ركن أساسي في العمارة الحديثة يجمع بين الأصالة والحداثة. يستعرض المؤلف أهم العناصر الجمالية التي تجعل من المجلس مساحة فريدة للحوار الفكري والاجتماعي.",
    coverImage: "https://images.unsplash.com/photo-1589998059171-988d887df646?auto=format&fit=crop&q=80&w=1000",
    category: "تاريخ الفن",
    pages: 320,
    language: "العربية",
    isbn: "978-3-16-148410-0",
    publishDate: "أكتوبر 2023",
    coverType: "غلاف فني صلب",
    isNew: true,
    rating: 4.5,
    reviewsCount: 124,
    discountPercentage: 15,
    stock: 20
  },
  {
    id: "2",
    title: "تاريخ الفلسفة العربية والحديثة",
    author: "د. محمد بن عبدالله",
    price: 85,
    description: "كتاب يستعرض الجذور الفلسفية وتطور الفكر العربي عبر العصور.",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=1000",
    category: "الفلسفة",
    pages: 450,
    language: "العربية",
    isbn: "978-0-12-345678-9",
    publishDate: "سبتمبر 2023",
    coverType: "غلاف عادي",
    isNew: true,
    rating: 4.8,
    reviewsCount: 89,
    stock: 5
  },
  {
    id: "3",
    title: "مدن الملح: التيه",
    author: "عبدالرحمن منيف",
    price: 120,
    description: "رواية ملحمية تتناول التحولات الاجتماعية والسياسية في منطقة الخليج.",
    coverImage: "https://images.unsplash.com/photo-1532012197367-e37a2df144e5?auto=format&fit=crop&q=80&w=1000",
    category: "الخيال",
    pages: 560,
    language: "العربية",
    isbn: "978-1-23-456789-0",
    publishDate: "مارس 2022",
    coverType: "غلاف عادي",
    rating: 4.9,
    reviewsCount: 230,
    discountPercentage: 20,
    stock: 0
  },
  {
    id: "4",
    title: "مقدمة ابن خلدون - طبعة فاخرة",
    author: "ابن خلدون",
    price: 250,
    description: "العمل التأسيسي في علم الاجتماع والتاريخ بتقديم معاصر وطباعة فاخرة.",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=1000",
    category: "التاريخ",
    pages: 800,
    language: "العربية",
    isbn: "978-2-34-567890-1",
    publishDate: "يناير 2021",
    coverType: "مجلد فاخر",
    rating: 5,
    reviewsCount: 540,
    stock: 12
  },
  {
    id: "5",
    title: "قواعد العشق الأربعون",
    author: "إليف شفق",
    price: 95,
    description: "رواية تتناول العلاقة بين جلال الدين الرومي وشمس التبريزي في إطار معاصر.",
    coverImage: "https://images.unsplash.com/photo-1474932430478-367dbb6832c1?auto=format&fit=crop&q=80&w=1000",
    category: "الخيال",
    pages: 400,
    language: "العربية",
    isbn: "978-6-03-012345-6",
    publishDate: "أبريل 2023",
    coverType: "غلاف عادي",
    rating: 4.7,
    reviewsCount: 310,
    stock: 15
  },
  {
    id: "6",
    title: "عالم سوبر وورلد",
    author: "هاروكي موراكامي",
    price: 110,
    description: "رحلة في عالم الواقعية السحرية والغموض الياباني المعاصر.",
    coverImage: "https://images.unsplash.com/photo-1543004218-ee141104239e?auto=format&fit=crop&q=80&w=1000",
    category: "روايات عالمية",
    pages: 380,
    language: "العربية",
    isbn: "978-9-87-654321-0",
    publishDate: "يونيو 2023",
    coverType: "غلاف فني",
    rating: 4.6,
    reviewsCount: 150,
    stock: 8
  }
];

export const EGYPT_GOVERNORATES = [
  "القاهرة",
  "الجيزة",
  "الإسكندرية",
  "الدقهلية",
  "البحر الأحمر",
  "البحيرة",
  "الفيوم",
  "الغربية",
  "الإسماعيلية",
  "المنوفية",
  "المنيا",
  "القليوبية",
  "الوادي الجديد",
  "السويس",
  "الشرقية",
  "الغردقة",
  "الطور",
  "شمال سيناء",
  "جنوب سيناء",
  "كفر الشيخ",
  "مطروح",
  "الأقصر",
  "قنا",
  "سوهج",
  "بني سويف",
  "أسيوط",
  "أسوان",
  "دمياط",
  "بورسعيد",
];
